### ISSUE TITLE
fatal error: reference to 'variant' is ambiguous

### ISSUE THREAD

**Issue by dongkaipo** [silverqx/TinyORM#13]
Hello, I encountered an error while compiling TinyORM on my Mac. Could you please help me identify where the error occurred?
![WX20230606-155057@2x](https://github.com/silverqx/TinyORM/assets/1720338/c07da464-5506-4c0e-9162-8826017833dc)

xcode version is 'Xcode 14.3.1 Build version 14E300c'

**Comment by silverqx** [comment]
Hi, macosx isn't supported as I don't have any macosx so I can't test it.

What compiler and which version do you use? I assume it's the Apple clang. What c++ library this compiler uses, it's libstdc++ or libc++? I'm asking because I know nothing about macosx c++ dev. env.

**Comment by SchaichAlonso** [comment]
Hi,

I can reproduce this on FreeBSD, using clang++ and libc++

It's caused by the `_LIBCPP_TEMPLATE_VIS` macro used by `std::variant` as defined in `<variant>` to become

    class __attribute__((__type_visibility__("default"))) variant;

while `std::variant` as defined in [orm/ormconcepts.hpp:20](https://github.com/silverqx/TinyORM/blob/0558c2fda0253d090477e36cc8aeb1054ab93049/include/orm/ormconcepts.hpp#L20) instead becomes

    class __attribute__((__visibility__("hidden"))) variant;

where the hidden originates in the [CXX_VISIBILITY_PRESET](https://github.com/silverqx/TinyORM/blob/0558c2fda0253d090477e36cc8aeb1054ab93049/CMakeLists.txt#L212) used by TinyORM.

Including `<variant>` instead of prototyping `std::variant` fixes this build failure.

**Comment by silverqx** [comment]
Are you able to compile it with `libc++` because I don't support it, the reason is that I wasn't able to compile a simple hello world programs with c++2a two years ago. 

I don't have any plans to add `libc++` support in the near future, it will cost much more effort to add it correctly.

The problem is as you wrote, I agree with that.

Much better would be something like this:
```
namespace std
{
#if defined(_LIBCPP_VERSION) && defined(_LIBCPP_TEMPLATE_VIS)
    template<typename ...Types>
    class _LIBCPP_TEMPLATE_VIS variant; // NOLINT(bugprone-forwarding-reference-overload)
#else
    template<typename ...Types>
    class variant; // NOLINT(bugprone-forwarding-reference-overload)
#endif
} // namespace std
```

Can you try it if it compiles correctly? Thx

**Comment by SchaichAlonso** [comment]
> Are you able to compile it with `libc++` because I don't support it, the reason is that I wasn't able to compile a simple hello world programs with c++2a two years ago.
> 
> I don't have any plans to add `libc++` support in the near future, it will cost much more effort to add it correctly.
> 
> The problem is as you wrote, I agree with that.
> 
> Much better would be something like this:
> 
> ```c++
> namespace std
> {
> #if defined(_LIBCPP_VERSION) && defined(_LIBCPP_TEMPLATE_VIS)
>     template<typename ...Types>
>     class _LIBCPP_TEMPLATE_VIS variant; // NOLINT(bugprone-forwarding-reference-overload)
> #else
>     template<typename ...Types>
>     class variant; // NOLINT(bugprone-forwarding-reference-overload)
> #endif
> } // namespace std
> ```
> 
> Can you try it if it compiles correctly? Thx

It fails to compile, reproducing the same error the OP has.

**Comment by silverqx** [comment]
I should merge it much sooner, that forward declaration was not a good idea anyway.
