### ISSUE TITLE
Timestamps get formated wrong

### ISSUE THREAD

**Issue by Redmanacac** [silverqx/TinyORM#48]
Hello,

as you can see
![image](https://github.com/user-attachments/assets/93f46e96-4900-460c-b4e6-a472c29ebd64)
there is a missing whitespace inbetween date and time.

I get there from ```performInsert```. In ```updateTimeStamps()``` the values generated are correct.

![image](https://github.com/user-attachments/assets/26f09544-05c9-416f-833b-c42feaa30355)

When finally inserting these are the bindings 
![image](https://github.com/user-attachments/assets/8cfb52c3-388c-4bdf-93b1-b1f6442bfabf)

When inserting a different model it seems to work
![image](https://github.com/user-attachments/assets/c918e627-5153-4a20-acff-fc2a33419a3d)

**Comment by silverqx** [comment]
It's too little info for me to reproduce it and this QDateTime conversion logic is soo complex.

The value you are referring to is after the conversions and the format of this value is based on the Model::u_dateFormat (but only when the Model::u_timestamps is true). It's described [here](https://www.tinyorm.org/tinyorm/getting-started#timestamps).

To reproduce it I will need the model class (it doesn't have to be complete, only what relates to this QDateTime bug) and the command that I can invoke to reproduce it eg. Model::save() with all values.

Because I have tried it now and can't reproduce it.

There are also other things or logic that relates to converting timezones (qt_timezone database configuration option) which also touches/modifies these QDateTime values, but for now we can ignore this as it would be too confusing.

**Comment by silverqx** [comment]
I'd also like to fix it in the next release if the problem you're describing really exists. 😁

**Comment by silverqx** [comment]
And the next thing is that there are pretty big changes in the code that relates to this QDateTime formatting in the `develop` branch. Would be also good to test this `develop` branch whether you can reproduce it.

**Comment by Redmanacac** [comment]
Hey Silver,

I was so deep into debugging yesterday that I did not notice that 
```
/*! The storage format of the model's date columns. */
   inline static QString u_dateFormat{QStringLiteral("yyyy-MM-ddHH:mm:ss.z")};
```

produced the error

**Comment by silverqx** [comment]
Thats normal 😁.
